version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test --coverage
      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
      - run: flutter -v build apk
